/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blood_donation;

//import com.itextpdf.text.*;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Font;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.util.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *

 */
public class first extends javax.swing.JFrame {
    
    Connection con;
    PreparedStatement ps;
    Statement s;
    ResultSet rs;

    /**
     * Creates new form first
     */
    public first() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        sid = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        blood_group = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        bname = new javax.swing.JTextField();
        baddress = new javax.swing.JTextField();
        bdn = new javax.swing.JTextField();
        bcontact = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        del = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        combobox = new javax.swing.JComboBox<>();
        search = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pid = new javax.swing.JTextField();
        pname = new javax.swing.JTextField();
        pd = new javax.swing.JTextField();
        pbg = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        dpid = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(51, 153, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("Name:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(40, 70, 60, 18);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setText("ID:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(40, 120, 35, 18);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setText("Blood Group:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(40, 150, 84, 18);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setText("Address:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(40, 210, 70, 18);

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel9.setText("Contact:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(40, 250, 60, 18);

        name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                nameMouseReleased(evt);
            }
        });
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameKeyReleased(evt);
            }
        });
        jPanel2.add(name);
        name.setBounds(150, 70, 200, 30);

        id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                idMouseReleased(evt);
            }
        });
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idKeyReleased(evt);
            }
        });
        jPanel2.add(id);
        id.setBounds(150, 110, 200, 30);
        jPanel2.add(address);
        address.setBounds(150, 200, 200, 30);
        jPanel2.add(contact);
        contact.setBounds(150, 250, 200, 30);

        jButton6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton6.setText("ADD");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(40, 310, 79, 27);

        jButton7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton7.setText("RESET");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);
        jButton7.setBounds(240, 310, 73, 27);

        jButton9.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton9.setText("DELETE");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9);
        jButton9.setBounds(210, 410, 95, 27);

        jButton10.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton10.setText("UPDATE");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10);
        jButton10.setBounds(140, 310, 85, 27);
        jPanel2.add(sid);
        sid.setBounds(22, 410, 160, 30);

        jButton11.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton11.setText("GENERATE REPORT");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton11);
        jButton11.setBounds(90, 360, 159, 27);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "ID", "Blood Group", "Address", "Contact"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(620, 70, 452, 402);

        blood_group.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "B+", "AB+", "O+", "A-", "B-", "AB-", "O-" }));
        blood_group.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                blood_groupItemStateChanged(evt);
            }
        });
        blood_group.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                blood_groupKeyReleased(evt);
            }
        });
        jPanel2.add(blood_group);
        blood_group.setBounds(150, 150, 200, 30);

        jLabel15.setFont(new java.awt.Font("Gabriola", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 0, 102));
        jLabel15.setText("Donor Information");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(120, 0, 450, 62);

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "name", "id", " " }));
        jPanel2.add(jComboBox2);
        jComboBox2.setBounds(650, 30, 140, 30);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });
        jPanel2.add(jTextField2);
        jTextField2.setBounds(860, 30, 200, 30);

        jLabel17.setIcon(new javax.swing.ImageIcon("D:\\icons8-search-24.png")); // NOI18N
        jPanel2.add(jLabel17);
        jLabel17.setBounds(820, 40, 24, 20);

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aishwarya\\Downloads\\08f85946664dd7cc6a3a87563b8daac3.jpg")); // NOI18N
        jPanel2.add(jLabel20);
        jLabel20.setBounds(0, 0, 2240, 900);

        jTabbedPane1.addTab("Donor", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Blood Bank Name:");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(20, 90, 130, 18);

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Address:");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(20, 130, 56, 18);

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Blood Bank Donor Name:");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(20, 170, 159, 18);

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Contact:");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(20, 200, 70, 18);

        bname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bnameKeyReleased(evt);
            }
        });
        jPanel3.add(bname);
        bname.setBounds(210, 80, 200, 30);
        jPanel3.add(baddress);
        baddress.setBounds(210, 120, 200, 30);
        jPanel3.add(bdn);
        bdn.setBounds(210, 160, 200, 30);

        bcontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcontactActionPerformed(evt);
            }
        });
        jPanel3.add(bcontact);
        bcontact.setBounds(210, 200, 200, 30);

        jButton12.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton12.setText("ADD");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton12);
        jButton12.setBounds(50, 260, 75, 27);

        jButton13.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton13.setText("RESET");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton13);
        jButton13.setBounds(150, 260, 73, 27);

        jButton15.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton15.setText("UPDATE");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton15);
        jButton15.setBounds(250, 260, 85, 27);

        jButton16.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton16.setText("DELETE");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton16);
        jButton16.setBounds(230, 310, 97, 27);

        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        jPanel3.add(del);
        del.setBounds(40, 310, 150, 27);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Blood Bank  Name", " Address", "Blood Bank Donor Name", "Contact"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jPanel3.add(jScrollPane4);
        jScrollPane4.setBounds(560, 80, 452, 310);

        jLabel16.setFont(new java.awt.Font("Gabriola", 1, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 204, 204));
        jLabel16.setText("Blood Bank Information");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(110, 10, 370, 60);

        combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blood_bank_name", "Address", "Donor_name", " " }));
        jPanel3.add(combobox);
        combobox.setBounds(597, 40, 170, 30);

        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        jPanel3.add(search);
        search.setBounds(804, 40, 170, 30);

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aishwarya\\Desktop\\aa.jpg")); // NOI18N
        jPanel3.add(jLabel18);
        jLabel18.setBounds(0, 0, 1420, 850);

        jTabbedPane1.addTab("Blood Bank", jPanel3);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setText("Name:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 100, 50, 18);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setText("Id:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 150, 35, 18);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("Blood Group:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 190, 87, 27);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setText("Disease:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 250, 55, 18);

        pid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pidActionPerformed(evt);
            }
        });
        pid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pidKeyTyped(evt);
            }
        });
        jPanel1.add(pid);
        pid.setBounds(200, 140, 192, 30);

        pname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnameActionPerformed(evt);
            }
        });
        pname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pnameKeyReleased(evt);
            }
        });
        jPanel1.add(pname);
        pname.setBounds(200, 90, 192, 30);

        pd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdActionPerformed(evt);
            }
        });
        jPanel1.add(pd);
        pd.setBounds(200, 240, 192, 30);

        pbg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "B+", "AB+", "O+", "A-", "B-", "AB-", "O-" }));
        pbg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbgActionPerformed(evt);
            }
        });
        jPanel1.add(pbg);
        pbg.setBounds(200, 190, 192, 30);

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(50, 320, 82, 27);

        jButton2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton2.setText("UPDATE");
        jPanel1.add(jButton2);
        jButton2.setBounds(277, 2312, 85, 23);

        jButton3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(250, 380, 85, 27);

        jButton5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton5.setText("RESET");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(280, 320, 73, 30);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "ID", "Blood Group", "Disease"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(800, 130, 426, 353);

        dpid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpidActionPerformed(evt);
            }
        });
        jPanel1.add(dpid);
        dpid.setBounds(47, 380, 160, 30);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6);
        jTextField6.setBounds(97, 2314, 147, 20);

        jLabel14.setFont(new java.awt.Font("Gabriola", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 0, 51));
        jLabel14.setText("Patient Information");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(440, 70, 350, 62);

        jButton4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton4.setText("UPDATE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(160, 320, 90, 30);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "name", "id", "Disease" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(800, 90, 180, 30);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(1030, 90, 170, 30);

        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aishwarya\\Desktop\\blood_01.jpg")); // NOI18N
        jPanel1.add(jLabel21);
        jLabel21.setBounds(-270, -10, 1890, 910);

        jTabbedPane1.addTab("Patient Data", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1276, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pidActionPerformed

    private void pnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnameActionPerformed

    private void pdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pdActionPerformed

    private void pbgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pbgActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       
        //insering value to the Donar Table
        con=Blood_donation.Connerdb();
        try
        {
            String query="insert into Donor(name,id,blood_group,address,contact) values ('"+name.getText()+"','"+id.getText()+"','"+blood_group.getSelectedItem()+"','"+address.getText()+"','"+contact.getText()+"')";
            Statement s=con.createStatement();
            rs=s.executeQuery(query);
            if(rs.next())
            {
                JOptionPane.showMessageDialog(null,"Data Inserted Sucessfully...");
            }
        }
        catch(Exception e)
        {
                JOptionPane.showMessageDialog(null,"Error during data Inserting...");
        }
        
        fetch();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
     
        //Set value to the Reset Button
        
        name.setText("");
        id.setText("");
       // blood_group.setText("");
        address.setText("");
        contact.setText("");
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
     
        //Delete value from the Donor table
        
        con=Blood_donation.Connerdb();
        try
        {
            String query1="delete from Donor where id='"+sid.getText()+"'";
            s=con.createStatement();
            rs=s.executeQuery(query1);
            if(rs.next())
            {
                JOptionPane.showMessageDialog(null,"Data Deleted sucessfully...");
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Error");
            }
        }
        catch(Exception e)
        {
            
        }
        fetch();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        
        //Update Value of Donor table
        con=Blood_donation.Connerdb();
        try
        {
            String query="update Donor set name='"+name.getText()+"',address='"+address.getText()+"',contact='"+contact.getText()+"'where id='"+id.getText()+"'";
            s=con.createStatement();
            rs=s.executeQuery(query);
            //jTable3.setModel(DbUtils.resultSetToTableModel(rs));
            if(rs.next())
            {
                JOptionPane.showMessageDialog(null,"Data Updated...");
            }
        }
        catch(Exception e)
        {
            
        }
        fetch();
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void idMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idMouseReleased
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_idMouseReleased

    private void nameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameMouseReleased
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_nameMouseReleased

    private void nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyReleased
        
    }//GEN-LAST:event_nameKeyReleased

    private void idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyReleased
        
    }//GEN-LAST:event_idKeyReleased

    private void blood_groupKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_blood_groupKeyReleased
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_blood_groupKeyReleased

    private void blood_groupItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_blood_groupItemStateChanged
        
        
        //Serach Value Accroding to Blood Group
        
        
         con=Blood_donation.Connerdb();
        try
        {
           
          PreparedStatement ps=con.prepareStatement("select * from Donor where blood_group=?");
         ps.setString(1,String.valueOf(blood_group.getSelectedItem()));
         ResultSet rs=ps.executeQuery();
         jTable3.setModel(DbUtils.resultSetToTableModel(rs));
         ps.close(); 
        }
        catch(Exception e)
        {
            
        }
        
        
    }//GEN-LAST:event_blood_groupItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        //Insert Value to the patient table
        
         con=Blood_donation.Connerdb();
        try
        {
            String query="insert into patient(name,id,blood_group,disease) values ('"+pname.getText()+"','"+pid.getText()+"','"+pbg.getSelectedItem()+"','"+pd.getText()+"')";
            Statement s=con.createStatement();
            rs=s.executeQuery(query);
           // jTable2.setModel(DbUtils.resultSetToTableModel(rs));
            if(rs.next())
            {
                JOptionPane.showMessageDialog(null,"Data Inserted Sucessfully...");
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Error during data Inserting...");
            }
        }
        catch(Exception e)
        {
                
        }
        
        fetch1();
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        pname.setText("");
        pid.setText("");
       // pbg.setText("");
        pd.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        //delete value from patient table
        
        con=Blood_donation.Connerdb();
        try
        {
           String query="delete from patient where id='"+dpid.getText()+"'" ;
           s=con.createStatement();
           rs=s.executeQuery(query);
           if(rs.next())
           {
               JOptionPane.showMessageDialog(null, "Data Deleted Sucessfully");
           }
           else
           {
               JOptionPane.showMessageDialog(null,"Errror");
           }
        }
        catch(Exception e)
        {
            
        }
        fetch1();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void pnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pnameKeyReleased
        
    }//GEN-LAST:event_pnameKeyReleased

    private void pidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pidKeyTyped
      
    }//GEN-LAST:event_pidKeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
    //Update value of patient table
        
        con=Blood_donation.Connerdb();
        try
        {
            String query="update patient set name='"+pname.getText()+"',disease='"+pd.getText()+"'where id='"+pid.getText()+"'";
            s=con.createStatement();
            rs=s.executeQuery(query);
            //jTable3.setModel(DbUtils.resultSetToTableModel(rs));
            if(rs.next())
            {
                JOptionPane.showMessageDialog(null,"Data Updated...");
            }
        }
        catch(Exception e)
        {
            
        }
        fetch1();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        
        //Insert value into the blood bank Table
        
         con=Blood_donation.Connerdb();
        try
        {
            String query="insert into Blood(Blood_bank_name,Address,Donor_name,Contact) values ('"+bname.getText()+"','"+baddress.getText()+"','"+bdn.getText()+"','"+bcontact.getText()+"')";
            Statement s=con.createStatement();
            rs=s.executeQuery(query);
            if(rs.next())
            {
                JOptionPane.showMessageDialog(null,"Data Inserted Sucessfully...");
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Error during data Inserting...");
            }
        }
        catch(Exception e)
        {
                
        }
        
        fetch2();
     
        
        
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

        //Generate Report
        
         Document doc = new Document();
        try {
            PdfWriter.getInstance(doc,new FileOutputStream("report1.pdf"));
            doc.open();
            doc.add(new Paragraph("Blood Donation Report",FontFactory.getFont(FontFactory.TIMES_ROMAN, 18,Font.BOLD,BaseColor.RED)));
            doc.add(new Paragraph("                                                                                                    "+new Date().toString()));
            //doc.add(new Paragraph(new Date().toString()));
           
            doc.add(new Paragraph("_____________________________________________________________________________"));
              doc.add(new Paragraph("ID: "+id.getText().toString(),FontFactory.getFont(FontFactory.TIMES_ROMAN,15,Font.BOLD,BaseColor.BLACK)));
              doc.add(new Paragraph("Name: "+name.getText().toString(),FontFactory.getFont(FontFactory.TIMES_ROMAN,15,Font.BOLD,BaseColor.BLACK)));
            doc.add(new Paragraph("Blood Group: "+blood_group.getSelectedItem().toString(),FontFactory.getFont(FontFactory.TIMES_ROMAN,15,Font.BOLD,BaseColor.BLACK)));
              doc.add(new Paragraph("Contact: "+contact.getText().toString(),FontFactory.getFont(FontFactory.TIMES_ROMAN,15,Font.BOLD,BaseColor.BLACK)));
               doc.add(new Paragraph("Address: "+address.getText().toString(),FontFactory.getFont(FontFactory.TIMES_ROMAN,15,Font.BOLD,BaseColor.BLACK)));
            JOptionPane.showMessageDialog(null, "Report Saved");
            doc.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(first.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(first.class.getName()).log(Level.SEVERE, null, ex);
        }

       


        
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        
        //Update value of Blood bank Table
        
        con=Blood_donation.Connerdb();
        try
        {
           String query="update Blood set Contact='"+bcontact.getText()+"'where Blood_bank_name='"+bname.getText()+"'" ;
           s=con.createStatement();
           rs=s.executeQuery(query);
           if(rs.next())
           {
               JOptionPane.showMessageDialog(null,"Data Updated");
           }
           else
           {
               JOptionPane.showMessageDialog(null, "Error");
           }
        }
        catch(Exception e)
        {
            
        }
        fetch2();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        bname.setText("");
        baddress.setText("");
        bdn.setText("");
        bcontact.setText("");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        
        //Delete value of Blood bank table
        
        con=Blood_donation.Connerdb();
        try
        {
            String query="delete from Blood where Blood_bank_name='"+del.getText()+"'";
            s=con.createStatement();
            rs=s.executeQuery(query);
            if(rs.next())
            {
                JOptionPane.showMessageDialog(null,"Data Deleted");
            }
        }
        catch(Exception e)
        {
            
        }
        fetch2();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void bnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bnameKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_bnameKeyReleased

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        
        //Serach value in the Blood Bank Table
        
        con=Blood_donation.Connerdb();
        try
        {
            String Selection=(String)combobox.getSelectedItem();
             PreparedStatement ps=con.prepareStatement("select * from Blood where "+Selection+"=?");
            ps.setString(1,String.valueOf(search.getText()));
            ResultSet rs=ps.executeQuery();
            jTable4.setModel(DbUtils.resultSetToTableModel(rs));
           
            while(rs.next())
            {
                
            }
             ps.close();
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_searchKeyReleased

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
     
        //Serach value in to the patient table
        
        con=Blood_donation.Connerdb();
        try
        {
            String Selection=(String)jComboBox1.getSelectedItem();
             PreparedStatement ps=con.prepareStatement("select * from  patient where "+Selection+"=?");
            ps.setString(1,String.valueOf(jTextField1.getText()));
            ResultSet rs=ps.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
           
            while(rs.next())
            {
                
            }
             ps.close();
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        
        //search value in to the Donor table
        
        con=Blood_donation.Connerdb();
        try
        {
            String Selection=(String)jComboBox2.getSelectedItem();
             PreparedStatement ps=con.prepareStatement("select * from Donor where "+Selection+"=?");
            ps.setString(1,String.valueOf(jTextField2.getText()));
            ResultSet rs=ps.executeQuery();
            jTable3.setModel(DbUtils.resultSetToTableModel(rs));
           
            while(rs.next())
            {
                
            }
             ps.close();
        }
        catch(Exception e)
        {
            
        }
        
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void dpidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dpidActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delActionPerformed

    private void bcontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcontactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bcontactActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    
    public void fetch()
    {
        try
        {
        String Query3="Select * from Donor";
        PreparedStatement ps=con.prepareStatement(Query3);
        rs=ps.executeQuery();
        jTable3.setModel(DbUtils.resultSetToTableModel(rs));
        
        }
        catch(Exception e)
        {
            
        }
        
        
    }
    
    
     public void fetch1()
    {
        try
        {
        String Query3="Select * from patient";
        PreparedStatement ps=con.prepareStatement(Query3);
        rs=ps.executeQuery();
        jTable2.setModel(DbUtils.resultSetToTableModel(rs));
        
        }
        catch(Exception e)
        {
            
        }
    }
        
         public void fetch2()
    {
        try
        {
        String Query3="Select * from Blood";
        PreparedStatement ps=con.prepareStatement(Query3);
        rs=ps.executeQuery();
        jTable4.setModel(DbUtils.resultSetToTableModel(rs));
        
        }
        catch(Exception e)
        {
            
        }
        
        //fetch2();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(first.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(first.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(first.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(first.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new first().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField baddress;
    private javax.swing.JTextField bcontact;
    private javax.swing.JTextField bdn;
    private javax.swing.JComboBox<String> blood_group;
    private javax.swing.JTextField bname;
    private javax.swing.JComboBox<String> combobox;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField del;
    private javax.swing.JTextField dpid;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField name;
    private javax.swing.JComboBox<String> pbg;
    private javax.swing.JTextField pd;
    private javax.swing.JTextField pid;
    private javax.swing.JTextField pname;
    private javax.swing.JTextField search;
    private javax.swing.JTextField sid;
    // End of variables declaration//GEN-END:variables
}
